#!/bin/bash

while getopts 'p:o:n:u:i:' OPTION; do
    case "$OPTION" in
        p)
            port=${OPTARG}
            ;;
        o)
            origin=${OPTARG}
            ;;
        i)
            keyfile=${OPTARG}
            ;;
        n)
            servername=${OPTARG}
            ;;
        u)
            username=${OPTARG}
            ;;
    esac
done
shift $((OPTIND-1))

make clean

rsync -a --exclude=".*" -e  "ssh -i $keyfile" ./HTTP $username@173.255.210.124:~

ssh -i $keyfile $username@173.255.210.124 <<EOF
cd HTTP
make -f HTTP.mk clean
make -f HTTP.mk
exit
EOF