#!/bin/bash

while getopts 'p:o:n:u:i:' OPTION; do
    case "$OPTION" in
        p)
            port=${OPTARG}
            ;;
        o)
            origin=${OPTARG}
            ;;
        i)
            keyfile=${OPTARG}
            ;;
        n)
            servername=${OPTARG}
            ;;
        u)
            username=${OPTARG}
            ;;
    esac
done
shift $((OPTIND-1))

# DNS
ssh -i $keyfile $username@97.107.140.73 <<EOF
mkdir DNS
mkdir IP2LOCATION
mkdir remotes
nohup sc_remoted -P 25009 -U remotes > scamper.out 2> scamper.err < /dev/null &
exit
EOF

scp -i $keyfile ./DNS/dnsserver $username@97.107.140.73:~/DNS
scp -i $keyfile ./DNS/servers.txt $username@97.107.140.73:~/DNS
scp -i $keyfile ./DNS/scamperscript $username@97.107.140.73:~/DNS
scp -i $keyfile ./IP2LOCATION/IPLocation.csv $username@97.107.140.73:~/IP2LOCATION

# #HTTP
while read server; do
    ssh -i $keyfile $username@$server <<EOF
    mkdir HTTP
    mkdir cache
    nohup scamper -R 97.107.140.73:25009 > scamper.out 2> scamper.err < /dev/null &
    exit
EOF

    scp -i $keyfile ./HTTP/httpserver $username@$server:HTTP
    scp -i $keyfile ./downloadCache $username@$server:~
    scp -i $keyfile ./pageviews.csv $username@$server:~


    ssh -i $keyfile $username@$server <<EOF
    ./downloadCache
    rm downloadCache
    rm pageviews.csv
    exit
EOF
done < ./DNS/servers.txt