#!/bin/bash

while getopts 'p:o:n:u:i:' OPTION; do
    case "$OPTION" in
        p)
            port=${OPTARG}
            ;;
        o)
            origin=${OPTARG}
            ;;
        i)
            keyfile=${OPTARG}
            ;;
        n)
            servername=${OPTARG}
            ;;
        u)
            username=${OPTARG}
            ;;
    esac
done
shift $((OPTIND-1))

make clean
rsync -a --exclude=".*" -e  "ssh -i $keyfile" . tjswierzewski@cs5700cdnproject.khoury.northeastern.edu:~/5700/project4

ssh -i $keyfile tjswierzewski@cs5700cdnproject.khoury.northeastern.edu <<EOF
cd 5700/project4
make clean
make
scp -i $keyfile ./dnsserver $username@97.107.140.73:~
EOF

        